#include "flash_usb_protocol.h"
#include "sst39sf040.h"
#include "usbd_cdc_if.h"   /* generated by CubeMX -- declares CDC_Transmit_FS() */
#include "stm32f4xx_hal.h"
#include <string.h>

/* ---------------- Wire protocol ----------------
 * Request:  [0xAA][CMD][LEN_LO][LEN_HI][PAYLOAD...][CRC8]
 * Response: [0x55][STATUS][LEN_LO][LEN_HI][PAYLOAD...][CRC8]
 * CRC8 is computed over CMD/STATUS + LEN + PAYLOAD (not the SOF byte).
 * Poly 0x07, init 0x00, no reflection, no final XOR -- matches the
 * crc8() function in the host-side program.py.
 */

#define FRAME_SOF_REQ   0xAAu
#define FRAME_SOF_RESP  0x55u

typedef enum {
    CMD_PING         = 0x01,
    CMD_GET_INFO     = 0x02,
    CMD_CHIP_ERASE   = 0x03,
    CMD_SECTOR_ERASE = 0x04,
    CMD_WRITE        = 0x05,
    CMD_READ         = 0x06,
} cmd_id_t;

typedef enum {
    STATUS_OK              = 0x00,
    STATUS_ERR_CRC          = 0x01,
    STATUS_ERR_TIMEOUT      = 0x02,
    STATUS_ERR_VERIFY       = 0x03,
    STATUS_ERR_ID           = 0x04,
    STATUS_ERR_RANGE        = 0x05,
    STATUS_ERR_UNKNOWN_CMD  = 0x06,
} resp_status_t;

#define MAX_CHUNK    512u                 /* max WRITE/READ data bytes per frame */
#define MAX_PAYLOAD  (4u + MAX_CHUNK)     /* WRITE payload = 4-byte addr + data  */
#define RX_STAGE_SIZE 1024u               /* staging buffer, must be > 5+MAX_PAYLOAD */

static volatile uint8_t  rx_stage[RX_STAGE_SIZE];
static volatile uint32_t rx_stage_len = 0;

/* ---------------- small helpers ---------------- */

static uint8_t crc8(const uint8_t *data, uint16_t len)
{
    uint8_t crc = 0x00u;
    for (uint16_t i = 0; i < len; i++) {
        crc ^= data[i];
        for (uint8_t b = 0; b < 8; b++) {
            crc = (crc & 0x80u) ? (uint8_t)((crc << 1) ^ 0x07u) : (uint8_t)(crc << 1);
        }
    }
    return crc;
}

static uint32_t get_u32_le(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

static void put_u32_le(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xFFu);
    p[1] = (uint8_t)((v >> 8) & 0xFFu);
    p[2] = (uint8_t)((v >> 16) & 0xFFu);
    p[3] = (uint8_t)((v >> 24) & 0xFFu);
}

static uint8_t map_status(sst_status_t st)
{
    switch (st) {
        case SST_OK:          return STATUS_OK;
        case SST_ERR_TIMEOUT: return STATUS_ERR_TIMEOUT;
        case SST_ERR_VERIFY:  return STATUS_ERR_VERIFY;
        case SST_ERR_ID:      return STATUS_ERR_ID;
        case SST_ERR_RANGE:   return STATUS_ERR_RANGE;
        default:               return STATUS_ERR_UNKNOWN_CMD;
    }
}

/* ---------------- USB RX staging (ISR-safe append) ---------------- */

void FlashProto_OnUsbRx(uint8_t *data, uint32_t len)
{
    uint32_t primask = __get_PRIMASK();
    __disable_irq();

    if (len <= (RX_STAGE_SIZE - rx_stage_len)) {
        memcpy((void *)&rx_stage[rx_stage_len], data, len);
        rx_stage_len += len;
    }
    /* else: staging buffer full -- drop the chunk. Shouldn't happen with
       the host's stop-and-wait protocol and default CDC RX buffer sizes. */

    if (!primask) __enable_irq();
}

static void consume(uint32_t n)
{
    uint32_t primask = __get_PRIMASK();
    __disable_irq();

    memmove((void *)rx_stage, (const void *)&rx_stage[n], rx_stage_len - n);
    rx_stage_len -= n;

    if (!primask) __enable_irq();
}

/* ---------------- response transmit ---------------- */

static void send_response(uint8_t status, const uint8_t *payload, uint16_t plen)
{
    static uint8_t tx_buf[8 + MAX_CHUNK];
    uint16_t idx = 0;

    tx_buf[idx++] = FRAME_SOF_RESP;
    tx_buf[idx++] = status;
    tx_buf[idx++] = (uint8_t)(plen & 0xFFu);
    tx_buf[idx++] = (uint8_t)((plen >> 8) & 0xFFu);
    if (plen) {
        memcpy(&tx_buf[idx], payload, plen);
        idx = (uint16_t)(idx + plen);
    }
    tx_buf[idx++] = crc8(&tx_buf[1], (uint16_t)(3 + plen));

    /* CDC_Transmit_FS returns USBD_BUSY if the previous transfer hasn't
     * completed yet -- retry briefly rather than dropping the response. */
    uint32_t start = HAL_GetTick();
    while (CDC_Transmit_FS(tx_buf, idx) != USBD_OK) {
        if (HAL_GetTick() - start > 1000u) break; /* give up after 1s */
    }
}

/* ---------------- command dispatch ---------------- */

static void handle_command(uint8_t cmd, const uint8_t *payload, uint16_t plen)
{
    switch (cmd) {

    case CMD_PING:
        send_response(STATUS_OK, NULL, 0);
        break;

    case CMD_GET_INFO: {
        uint8_t mfr = 0, dev = 0;
        sst_status_t st = SST_ReadID(&mfr, &dev);
        uint8_t resp[10];
        resp[0] = mfr;
        resp[1] = dev;
        put_u32_le(&resp[2], (uint32_t)SST_SIZE_BYTES);
        put_u32_le(&resp[6], SST_GetSectorSize());  /* reflects chip ID'd by SST_ReadID() above */
        send_response(map_status(st), resp, sizeof(resp));
        break;
    }

    case CMD_CHIP_ERASE: {
        sst_status_t st = SST_ChipErase();
        send_response(map_status(st), NULL, 0);
        break;
    }

    case CMD_SECTOR_ERASE: {
        if (plen != 4u) { send_response(STATUS_ERR_RANGE, NULL, 0); break; }
        uint32_t addr = get_u32_le(payload);
        sst_status_t st = SST_SectorErase(addr);
        send_response(map_status(st), NULL, 0);
        break;
    }

    case CMD_WRITE: {
        if (plen < 4u) { send_response(STATUS_ERR_RANGE, NULL, 0); break; }
        uint32_t addr      = get_u32_le(payload);
        const uint8_t *data = payload + 4;
        uint16_t dlen       = (uint16_t)(plen - 4u);
        sst_status_t st = SST_WriteBuffer(addr, data, dlen);
        send_response(map_status(st), NULL, 0);
        break;
    }

    case CMD_READ: {
        if (plen != 8u) { send_response(STATUS_ERR_RANGE, NULL, 0); break; }
        uint32_t addr = get_u32_le(payload);
        uint32_t len  = get_u32_le(payload + 4);
        if (len > MAX_CHUNK) { send_response(STATUS_ERR_RANGE, NULL, 0); break; }
        uint8_t buf[MAX_CHUNK];
        SST_ReadBuffer(addr, buf, len);
        send_response(STATUS_OK, buf, (uint16_t)len);
        break;
    }

    default:
        send_response(STATUS_ERR_UNKNOWN_CMD, NULL, 0);
        break;
    }
}

/* ---------------- frame parser ---------------- */

void FlashProto_Poll(void)
{
    /* resync: discard leading garbage until we see a request SOF */
    while (rx_stage_len > 0 && rx_stage[0] != FRAME_SOF_REQ) {
        consume(1);
    }

    if (rx_stage_len < 4u) return;   /* need SOF + CMD + LEN(2) at minimum */

    uint8_t  cmd  = rx_stage[1];
    uint16_t plen = (uint16_t)rx_stage[2] | ((uint16_t)rx_stage[3] << 8);

    if (plen > MAX_PAYLOAD) {
        /* bogus length -- drop the SOF byte and try to resync */
        consume(1);
        return;
    }

    uint32_t frame_total = 4u + plen + 1u; /* header + payload + crc */
    if (rx_stage_len < frame_total) return; /* wait for the rest to arrive */

    uint8_t crc_calc = crc8((const uint8_t *)&rx_stage[1], (uint16_t)(3u + plen));
    uint8_t crc_recv = rx_stage[4u + plen];

    if (crc_calc != crc_recv) {
        send_response(STATUS_ERR_CRC, NULL, 0);
        consume(frame_total);
        return;
    }

    handle_command(cmd, (const uint8_t *)&rx_stage[4], plen);
    consume(frame_total);
}
